#!/bin/bash

if [ $# -ne 1 ]
then
    echo "ERROR: Incorrect Usage"
    echo "kalxcorder <show-name>"
    exit 1
fi

SHOW=$1
YEAR=`date "+%Y"`
DATETIME=`date "+%m-%d_%H%M"`
FILENAME=$SHOW-$YEAR-$DATETIME.aac

# record the stream via vlc
$HOME/bin/vlcorder http://stream.kalx.berkeley.edu:8000/kalx-320.aac $HOME/tmp/$FILENAME
# update id3 metadata
id3 -a "KALX $SHOW" -l "$SHOW $YEAR" -t "$SHOW $DATETIME" -g "Acid" -y "$YEAR" $HOME/tmp/$FILENAME

mv $HOME/tmp/$FILENAME $HOME/GDrive/KALX

