#!/bin/bash
for arg in "$@"
do
    if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]
    then
        echo "vlcorder <url> <output-file>"
        echo "e.g. vlcorder http://live-mp3-128.kexp.org:80/kexp128.mp3 kexp.mp3"
        exit 0
    fi
done

if [ $# -ne 2 ]
then
    echo "incorrect args"
    exit 1
fi

streamripper $1 -l 3600 -a $2 -u 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0' -m 300 -d $HOME/tmp -s
